package com.timerly.timerlyplugin.models

object Constants {
    val COMMAND_FROM_SERVICE_STOP_CLICKED = "COMMAND_FROM_SERVICE_STOP_CLICKED"
    val COMMAND_FROM_SERVICE_LAP_CLICKED = "COMMAND_FROM_SERVICE_LAP_CLICKED"

    // Commands send from Services
    val COMMAND_FROM_SERVICE_BUTTON_1_CLICKED = "COMMAND_FROM_SERVICE_BUTTON_1_CLICKED"
    val COMMAND_FROM_SERVICE_BUTTON_2_CLICKED = "COMMAND_FROM_SERVICE_BUTTON_2_CLICKED"
    val COMMAND_FROM_SERVICE_BUTTON_CLOSE_CLICKED = "COMMAND_FROM_SERVICE_BUTTON_CLOSE_CLICKED"
    val COMMAND_FROM_SERVICE_BUTTON_OPEN_ACTIVITY = "COMMAND_FROM_SERVICE_BUTTON_OPEN_ACTIVITY"

    // Commands send to Services
    val COMMAND_TO_SERVICE_ADD = "COMMAND_TO_SERVICE_ADD"
    val COMMAND_TO_SERVICE_START = "COMMAND_TO_SERVICE_START"
    val COMMAND_TO_SERVICE_STOP = "COMMAND_TO_SERVICE_STOP"
    val COMMAND_TO_SERVICE_UPDATE_VALUE = "COMMAND_TO_SERVICE_UPDATE_VALUE"
    val COMMAND_TO_SERVICE_UPDATE_TITLE = "COMMAND_TO_SERVICE_UPDATE_TITLE"
    val COMMAND_TO_SERVICE_LAP = "COMMAND_TO_SERVICE_LAP"
    val COMMAND_TO_SERVICE_RESET = "COMMAND_TO_SERVICE_RESET"
    val COMMAND_TO_SERVICE_REMOVE = "COMMAND_TO_SERVICE_REMOVE"


}